default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: portfolio_development
  username: rails_user
  password: railsuserpassword

test:
  <<: *default
  database: portfolio_test
  username: rails_user
  password: railsuserpassword

production:
  <<: *default
  database: portfolio_production
  username: rails_user
  password: railsuserpassword 
